const mockTweets = [
  {
    id: 1,
    name: "John Doe",
    username: "john_doe",
    profileImage: "https://via.placeholder.com/150",
    content: "This is my first tweet on this platform!",
    timestamp: "2023-09-20T08:00:00Z",
    date: "Sep 20",
    likes: "126",
    retweets: "13",
    reply: "23",
  },
  {
    id: 2,
    name: "Alice Smith",
    username: "alice_smith",
    profileImage: "https://via.placeholder.com/150",
    content: "Checking out this new Twitter clone! 🚀",
    timestamp: "2023-09-20T07:45:00Z",
    date: "Sep 20",
    likes: "62",
    retweets: "32",
    reply: "17",
  },
  {
    id: 3,
    name: "Tech Guru",
    username: "tech_guru",
    profileImage: "https://via.placeholder.com/150",
    content:
      "Wondering if this platform supports threading of tweets. #thoughts",
    timestamp: "2023-09-20T07:30:00Z",
    date: "Sep 20",
    likes: "673",
    retweets: "287",
    reply: "126",
  },
  {
    id: 4,
    name: "Movie Buff",
    username: "movie_buff",
    profileImage: "https://via.placeholder.com/150",
    content: "Just watched the latest blockbuster. Highly recommend!",
    timestamp: "2023-09-20T07:15:00Z",
    date: "Sep 20",
    likes: "16",
    retweets: "3",
    reply: "7",
  },
  {
    id: 5,
    name: "Daily News",
    username: "daily_news",
    profileImage: "https://via.placeholder.com/150",
    content: "Breaking news: Major event just happened in the city!",
    timestamp: "2023-09-20T07:00:00Z",
    date: "Sep 20",
    likes: "469",
    retweets: "87",
    reply: "62",
  },
  {
    id: 6,
    name: "Nature Lover",
    username: "nature_lover",
    profileImage: "https://via.placeholder.com/150",
    content: "Took a morning hike and the view was absolutely stunning. 🌄",
    timestamp: "2023-09-20T06:45:00Z",
    date: "Sep 20",
    likes: "26",
    retweets: "14",
    reply: "9",
  },
  {
    id: 7,
    name: "Book Reader",
    username: "book_reader",
    profileImage: "https://via.placeholder.com/150",
    content:
      "Just finished reading a great book! Any recommendations for what I should read next?",
    timestamp: "2023-09-20T06:30:00Z",
    date: "Sep 20",
    likes: "243",
    retweets: "156",
    reply: "76",
  },
  {
    id: 8,
    name: "Chef Cook",
    username: "chef_cook",
    profileImage: "https://via.placeholder.com/150",
    content: "Whipped up some delicious pasta for dinner tonight. #ChefLife",
    timestamp: "2023-09-20T06:15:00Z",
    date: "Sep 20",
    likes: "215",
    retweets: "85",
    reply: "34",
  },
  {
    id: 9,
    name: "Traveler Joe",
    username: "traveler_joe",
    profileImage: "https://via.placeholder.com/150",
    content: "Just landed in Bali! Ready for an adventure. ✈️",
    timestamp: "2023-09-20T06:00:00Z",
    date: "Sep 20",
    likes: "945",
    retweets: "237",
    reply: "496",
  },
  {
    id: 10,
    name: "Fashionista",
    username: "fashionista",
    profileImage: "https://via.placeholder.com/150",
    content:
      "Shopping spree was a success! Got some trendy outfits for the season. #FashionForward",
    timestamp: "2023-09-20T05:45:00Z",
    date: "Sep 20",
    likes: "436",
    retweets: "353",
    reply: "234",
  },
];

const trendingHashtags = [
  {
    id: "1",
    category: "Science",
    hashtag: "#QuantumComputing",
    numberOfPosts: "8,900",
  },
  {
    id: "2",
    category: "Science",
    hashtag: "#VaccineDebate",
    numberOfPosts: "43.5K",
  },
  {
    id: "3",
    category: "Technology",
    hashtag: "#DeepFakeConcerns",
    numberOfPosts: "21K",
  },
  {
    id: "4",
    category: "Technology",
    hashtag: "#5GConspiracy",
    numberOfPosts: "31.7K",
  },
  {
    id: "5",
    category: "Politics",
    hashtag: "#ImpeachmentTalk",
    numberOfPosts: "72K",
  },
  {
    id: "6",
    category: "Politics",
    hashtag: "#CancelCulture",
    numberOfPosts: "62.9K",
  },
  {
    id: "7",
    category: "Sports",
    hashtag: "#TourDeFrance2023",
    numberOfPosts: "27K",
  },
  {
    id: "8",
    category: "Sports",
    hashtag: "#TakeAKnee",
    numberOfPosts: "44.1K",
  },
  {
    id: "9",
    category: "Entertainment",
    hashtag: "#OscarSnubs",
    numberOfPosts: "19.4K",
  },
  {
    id: "10",
    category: "Entertainment",
    hashtag: "#CelebrityBreakup",
    numberOfPosts: "25K",
  },
  {
    id: "11",
    category: "Business & Finance",
    hashtag: "#WallStreetProtests",
    numberOfPosts: "31K",
  },
  {
    id: "12",
    category: "Business & Finance",
    hashtag: "#GameStopSaga",
    numberOfPosts: "53K",
  },
  {
    id: "13",
    category: "Education",
    hashtag: "#SATScandal",
    numberOfPosts: "12.3K",
  },
  {
    id: "14",
    category: "Education",
    hashtag: "#StudentDebtCrisis",
    numberOfPosts: "21.5K",
  },
  {
    id: "15",
    category: "Health & Wellness",
    hashtag: "#AntiVaxMovement",
    numberOfPosts: "47K",
  },
  {
    id: "16",
    category: "Health & Wellness",
    hashtag: "#WellnessInfluencer",
    numberOfPosts: "17K",
  },
  {
    id: "17",
    category: "Travel",
    hashtag: "#FlightShaming",
    numberOfPosts: "9,900",
  },
  {
    id: "18",
    category: "Travel",
    hashtag: "#VanLife",
    numberOfPosts: "34K",
  },
  {
    id: "19",
    category: "Food & Drink",
    hashtag: "#ImpossibleBurgerDebate",
    numberOfPosts: "18K",
  },
  {
    id: "20",
    category: "Food & Drink",
    hashtag: "#EthicalEating",
    numberOfPosts: "9,200",
  },
];

export { mockTweets, trendingHashtags };
